// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create20190630 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create20190630));
        
        string IMigrationMetadata.Id
        {
            get { return "201906300123350_Create20190630"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
