// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create201911271650 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create201911271650));
        
        string IMigrationMetadata.Id
        {
            get { return "201911270850185_Create201911271650"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
